[package]
name = "mdbook-generate-summary"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = "4.2.1"
mdbook = "0.4.28"
anyhow = "1.0.70"
serde = "1.0.159"
serde_json = "1.0.95"
semver = "1.0.17"
toml = "0.5.8"
